<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <AssemblyName>JenkinsTray</AssemblyName>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <WindowsAppSdkBootstrapInitialize>false</WindowsAppSdkBootstrapInitialize>
    <ApplicationIcon>../../JenkinsTray/JenkinsTray.ico</ApplicationIcon>
    <Product>Jenkins Tray</Product>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../JenkinsTray.Desktop/JenkinsTray.Desktop.csproj" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
  </ItemGroup>
</Project>
